name: Deploy Hugo site to GitHub Pages

on:
    push:
        branches:
            - main  # Adjust if your source branch is different

jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: docs
        steps:
          - name: Checkout repository
            uses: actions/checkout@v3

          - name: Setup Hugo
            uses: peaceiris/actions-hugo@v2
            with:
                hugo-version: '0.144.1'  # Use your installed Hugo version
        
          - name: Build site
            run: hugo -D

          - name: Deploy to GitHub Pages
            uses: peaceiris/actions-gh-pages@v3
            with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_branch: gh-pages
                publish_dir: ./public
